module.exports = {
    rules: {
        'cssclassname-extends-from-parent': require('./rules/cssclassname-extends-from-parent'),
        'no-accessing-private-members': require('./rules/no-accessing-private-members'),
        'no-bind-within-jquery': require('./rules/no-bind-within-jquery'),
        'no-callbacks-where-promises': require('./rules/no-callbacks-where-promises'),
        'no-commented-out-tests': require('./rules/no-commented-out-tests'),
        'no-data-options-dot-notation': require('./rules/no-data-options-dot-notation'),
        'no-direct-p-pubsub-subscribe-call-in-modules': require('./rules/no-direct-p-pubsub-subscribe-call-in-modules'),
        'no-duplicate-jquery-selectors': require('./rules/no-duplicate-jquery-selectors'),
        'no-goog-provide': require('./rules/no-goog-provide'),
        'no-goog-require': require('./rules/no-goog-require'),
        'no-invalid-binds': require('./rules/no-invalid-binds'),
        'no-jquery-outside-of-render': require('./rules/no-jquery-outside-of-render'),
        'no-jquery-var-without-$': require('./rules/no-jquery-var-without-$'),
        'no-listen-childListen-bind': require('./rules/no-listen-childListen-bind'),
        'no-module-member-variables': require('./rules/no-module-member-variables'),
        'no-mutable-module-options': require('./rules/no-mutable-module-options'),
        'no-private-functions-without-annotation': require('./rules/no-private-functions-without-annotation'),
        'no-reassigning-keywords': require('./rules/no-reassigning-keywords'),
        'no-reassigning-of-pubsub-topic-in-module': require('./rules/no-reassigning-of-pubsub-topic-in-module'),
        'no-reassigning-requires': require('./rules/no-reassigning-requires'),
        'no-referencing-$el': require('./rules/no-referencing-$el'),
        'no-referencing-p-properties': require('./rules/no-referencing-p-properties'),
        'no-this-without-bind': require('./rules/no-this-without-bind'),
        'no-translation-outside-of-function': require('./rules/no-translation-outside-of-function'),
        'no-unassigned-requires': require('./rules/no-unassigned-requires'),
        'no-unhandled-promise-errors': require('./rules/no-unhandled-promise-errors'),
    }
};
